### ISSUE TITLE
Disable variation axes if font has no STAT table

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontview#13]
According to the OpenType 1.8 specification, variable fonts are required to have a STAT table. Since Windows will very likely require STAT in variable fonts, fontview should suppress the variation sliders if a font has no STAT. This will help font designers to build fonts that comply with the OpenType spec.

**Comment by behdad** [comment]
I'm strongly opposed to this.  In particular, there is no need for webfonts to have STAT table.  STAT table is marked required, exactly because Microsoft said they want it this way.  Doesn't mean everyone has to follow... We routinely diverge from the spec in such ways, for example a font without post table is perfectly fine.  Same about OS/2 table. Same about name table.  Basically what the spec calls required is "Windows requires".

**Comment by behdad** [comment]
cc @khaledhosny

**Comment by brawer** [comment]
Fair point.
