### ISSUE TITLE
enhancement: disable (or hide?) a slider in fontview when not really useful/useable

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontview#14]
For the font below (part of the log from building NotoSansSymbols) both **_custom_** and **_width_** are fixed and really cannot be changed. However, in fontview one still can move the sliders for both (if one had a variable font :-)), but with no results. It might be better to disable (or hide?) a slider in fontview when not really useful/useable.

....
Index of base master: 1
Building GX
Loading TTF masters
Axes:
{'custom': (100.0, 100.0, 100.0),
 'weight': (26.0, 90.0, 190.0),
 'width': (100.0, 100.0, 100.0)}
Master locations:
[{'custom': 100.0, 'weight': 26.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 90.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 190.0, 'width': 100.0}]
Normalized master locations:
[{'custom': 0, 'weight': -1.0, 'width': 0},
 {'custom': 0, 'weight': 0, 'width': 0},
 {'custom': 0, 'weight': 1.0, 'width': 0}]
Building variations tables
Generating gvar
Merging OpenType Layout tables
Merging GPOS
.....

**Comment by brawer** [comment]
Actually, I think this is a bug in the font production pipeline. A font’s `fvar` table should only contain axes that actually work, and make sense to display. Of course fontview could try to detect this problem and work around it, but we can’t expect that every tool will work around broken fonts. Instead, the bug should be fixed in fontmake. Filed https://github.com/googlei18n/fontmake/issues/211 to keep track of this.
