### ISSUE TITLE
Variation is not showing up

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/fontview#18]
I have made a small test font that has two axis (weight/width) and three masters (regular, bold, extended). If I export the font from Glyphs, the axis sliders are shown in fontview but aren’t variating the outlines. I tested the font in Webkit nightly and it worked fine. If I add a forth master (bold extended), then it works in fontview, too.

[BlaBlaGX.ttf.zip](https://github.com/googlei18n/fontview/files/737757/BlaBlaGX.ttf.zip)
Only the uppercase A has outlines with variation.

**Comment by brawer** [comment]
FreeType’s `ftgrid` tool doesn’t vary the A glyph either, so the problem is probably in FreeType. Filed [FreeType bug 50184](https://savannah.nongnu.org/bugs/index.php?50184).

**Comment by brawer** [comment]
Thanks for the report! Werner Lemberg just fixed FreeType master. Once he cuts a new FreeType release (hopefully soon), it’ll flow downstream into FontView.

@schriftgestalt, would you be able to build a test font that shows the same problem with a glyph that isn’t just a period, and contribute that to Unicode? One glyph is enough; perhaps a black square (U+25A0) or a plus sign, just something more visible than a small dot... It would be great to add a test case to Unicode’s [text rendering tests](https://github.com/unicode-org/text-rendering-tests), since this will help other OpenType implementations (CoreText, DirectDraw, and others) to make sure they don’t run into the same problem. See [here](https://raw.githack.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html) for how the test suite looks. If you send a pull request to the [Unicode repo](https://github.com/unicode-org/text-rendering-tests) for adding the font to the `fonts` directory, a bot will ask you to sign Unicode’s contributor licensing agreement. Once the font is in the repo, I’ll gladly add a test case to the testing framework.

**Comment by schriftgestalt** [comment]
I'll have a look. 
The dot is supposed to become much bigger by the variation. It grows vertically by weight and horizontally by width. 
I can scale it up to make it more visible.

**Comment by schriftgestalt** [comment]
I did some more testing, If there are less then 14 glyphs (except .notdef and space), then it works. It doesn’t seem to matter what glyphs. The fvar and gvar table are identical in both files.
I’m not sure if such an obscure error needs to be put in an testing repo?
[BlaBlaaltGX test 2.zip](https://github.com/googlei18n/fontview/files/743027/BlaBlaaltGX.test.2.zip)
I made the dot a bit bigger. I like it like that, if you drag the working font into fontview, it will show the Bold instance that contains a 1000 units tall black bar so you see the difference very clearly.
